# This actually is not recommended - create a secret using 
#    echo -n PASSWORD | base64
# then create the secret using command line 
#    kubectl create secret generic db-secret --from-literal=password='your-db-password'
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo
type: Opaque
data:
  password: UEFTU1dPUkQ=