apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev", "--hostname-strict=false"]
          env:
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: "admin"
            - name: KEYCLOAK_ADMIN
              value: "root"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "PASSWORD"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HOSTNAME
              value: traefik.auth.localdev.me
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: "jdbc:mysql://mysql-server:3306/keycloak?createDatabaseIfNotExist=true"
            - name: KC_DB_USERNAME
              value: "root"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: "521Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: keycloak-app
  type: ClusterIP
