apiVersion: v1
data: 
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZzQ0ZEUC9VcnZudVFBM2wvOVc1
    OEp1bXBGcGJkb3BNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1FWXgKQ3pBSkJnTlZCQVlUQWtKU01ROHdE
    UVlEVlFRSURBWlFZWEpoYm1FeEVUQVBCZ05WQkFjTUNFTjFjbWwwYVdKaApNUk13RVFZRFZRUUtE
    QXBFWlhJZ1UyOXRiV1Z5TUI0WERUSTBNRE14TlRJeE1UVXdNbG9YRFRNME1ETXhNekl4Ck1UVXdN
    bG93UmpFTE1Ba0dBMVVFQmhNQ1FsSXhEekFOQmdOVkJBZ01CbEJoY21GdVlURVJNQThHQTFVRUJ3
    d0kKUTNWeWFYUnBZbUV4RXpBUkJnTlZCQW9NQ2tSbGNpQlRiMjF0WlhJd2dnRWlNQTBHQ1NxR1NJ
    YjNEUUVCQVFVQQpBNElCRHdBd2dnRUtBb0lCQVFESWZnSkxKL01aZnlWYnRmR0t6ZDVhcnBndExy
    eEVaVGFjRS9wMFVUTHoyTGxyCm4rSU1rOGlrYVFyUTZjeVlBNVNWSERPc1JXN2kwZ1VLek5MbFkw
    a2czaExVMmh2dFpJTFZEcndzN0c4ZUR1OUoKRmtYNFdHdkFHNFB1djVpVFg0R0RwL1grdnJFMGd4
    WmRzWTJFVnlGTHhZQ1ZBS2RIWWo4OFF5cGorSEpleVh3NwpjR0hDa0JDYVlPMGd3S0dDbXRWVTlh
    SGZTQTlJNGtlMlhqL0hpbkNTN2RITURYWi9aVXRLYXBBc0FqWDFuOG5WCkNMbUMxYUNLZWFmdWhS
    QllKK0JlR085c1BKVnRmMzVoL2tsam02YVdtQ1hoZGs1eUxiWHJqNndOTUFDa3VtVncKVmwrczlV
    OXFtYTRWSUVVcHJ3Wmo0VWVuSi83THk0MWp5cGJSeWwvTkFnTUJBQUV3RFFZSktvWklodmNOQVFF
    TApCUUFEZ2dFQkFNR1ZpUU1qdlZYTytvVzZsd0NQekx0TEh5Rmd2VVYrN1JET1RsYkQ1dlhIdGx0
    YWFweElrSjROCk9QOEJyMlJEWFNiZFQzN3BTK291ZkR4cXhQeG94TTgrckYzVEhUWGszRFl0bE9N
    aHhGbFNqU1ltUWJoNTlsMzEKN0VCV1BFZyszdnlhNlhDcGtKQzhKUU9Ob1RoSGxYYzVzK3R2V1dq
    SGlMZG43eU9UQmRnVFJiZnpvR2NoVkxocwpKWVZHbjExNktRLytrbXA2RXc3MTVIU3NWNUl4R2pl
    UGI1KytXbHIxUThtbnhBKzE1akd2a2FCY2R2OUNicFJhCjlZd2xaVlVyWU1zYkEwZXFzdll3ZWlk
    TmwvYjNWY3lxNEhxQm5QbnBRQlp6MS9FVXhoR21neUwxd0RHNUlid2oKSnZNNUorZ0ozNTFGdStt
    NGxrWlJ5ZDg3Snl4NWlHND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRRElmZ0pMSi9NWmZ5VmIKdGZHS3pkNWFycGd0THJ4RVpUYWNF
    L3AwVVRMejJMbHJuK0lNazhpa2FRclE2Y3lZQTVTVkhET3NSVzdpMGdVSwp6TkxsWTBrZzNoTFUy
    aHZ0WklMVkRyd3M3RzhlRHU5SkZrWDRXR3ZBRzRQdXY1aVRYNEdEcC9YK3ZyRTBneFpkCnNZMkVW
    eUZMeFlDVkFLZEhZajg4UXlwaitISmV5WHc3Y0dIQ2tCQ2FZTzBnd0tHQ210VlU5YUhmU0E5STRr
    ZTIKWGovSGluQ1M3ZEhNRFhaL1pVdEthcEFzQWpYMW44blZDTG1DMWFDS2VhZnVoUkJZSitCZUdP
    OXNQSlZ0ZjM1aAova2xqbTZhV21DWGhkazV5TGJYcmo2d05NQUNrdW1Wd1ZsK3M5VTlxbWE0VklF
    VXByd1pqNFVlbkovN0x5NDFqCnlwYlJ5bC9OQWdNQkFBRUNnZ0VBWTRNTHYyTHFTZWJ1VTNsWWxK
    VCsvdEoyN01Jc0p1UjN1UHMvamhrNWFZZlIKN0lYVWJIcXpsVXNmMTdhYjJuMjRjMVFtbjZSczE3
    NzNTcmVFRzkvdVRaWjhFVkxhbHJjVEt3M2Z2NHB3MHFJRwpDYWc0L1gxaHFkM2VXNU9VZHQxcUNy
    OUVuWGJudkpFdCtqNGs2Q0ZaQU9OY0lWak1MbVdvemsvbUMrMm1VcjNiCnZzQ1FZVGFOQzY4eE02
    dDZFdnpLRGRrMkhRSzVKTmphYlNKOWIxViszYWpKR3J0UDlmU3gvSXhVaVJEb3lDdW8KVHF4V1Fm
    QlloaGw1SnZzNGw5WnY2RndtZERhNS9SdVZpL2tYQVJaUlBEcktjSjJrajZvV1pjbEZ0V3diNXZY
    cApTdTBRM3gvK2c0ZWJQK3czQmNOVm9STzJweGZOZmgrVFM5Z2YvZ0ZEUHdLQmdRRE1DQm5YdUNG
    WlJxSFFoYnBrCnBBYW9GNTBFaVhnS29OemNKYXlGbTB5VVFHbXF3Yk12MllIOTVoWitLek9UeFFX
    NGJJZ1JQcEIrL2xPQ3dTcTcKY3JVWXpSRGZZY29OU2dMa2g0cWdqQnovME1mUzlBNnJZOUI4eTVR
    Z3VYVkVEaGpGVDdOdndvcHpnbUx1NHNhMApidWVwWEhCS2toaExGbXh2aUEwWjFtT0Ixd0tCZ1FE
    N2p4Nm5OWFJhVzFIT1Q4NGphZ1ZiN205dkc5L3dJbnVRCkV3ZkVCUVNiekhvTW05eTBUb2lLcjRj
    a1pXNEV0OHduS28xMFdaUEt6ZlJIWG10a3E5anhPMlczcGxUWUw1Z2MKQStIb0s2SnhHRWlVbVho
    c0cvQlRQaHFRWU1xS2dzcmd6dnh4ekE1UmVpYVJYWWx4YkQ2MGkxNG1YN1Yyc1ZwMgpUMmNQbUhn
    Kyt3S0JnUUMzNmZsNWhVV3lWc1BYMWlOOVFvbXBqWmVCRm5WNWh5VnU0QnJTV0huQURRdnkyeVd0
    ClZUQWk4UHVIZ1dPOXFOU09PRzZ5dEtYRmczVTlvT2ZuRGZBR1Noc1NjUENUNkFvUmU4aFBEZDI2
    RHJXQkIzUU4KdEN5andWSmw2U2EyVU1xdFdUbVMzVmExNW10TmtHZXpEMkdOUFlFUEJ3QVU5MEtK
    aXFiY2ltOHFBd0tCZ0Q3VQp5M0kySHI2bXluTCthZDFja01RYWRNaktySTg4L2FISnJ3bmR1djN5
    LzVVQXBRcUFCd2lrdU50MVhocGRrZWRDCmNKeGI5MWNUUSsxRGZ3MWhBc21WN1YwR2RYQ2R5cDlN
    dFBNWld2Um1mVkpvVnJTaDhjL0kxamV6aFVNOVVkRCsKd2Z6bVc3a3NDbEFLamRhL2s1WGlyWHht
    TVZ2WkJtQkFpdHhSVjg5YkFvR0FYTVBZb1J1K01Sd050cnYxV3R5WQpZTnRsb1BmeXJJSjUwYmEv
    YjV4dFc4Q3FJY2tVSkYwcGxPK3hxOTlHUkhjNU1HNG5IbzhPRWpwcVlnNmM4ZFoxCkZGWitoWjM2
    Q0VJN0VUTFU1R2F5NU9DVWM0d1ZKby9zbktSbC9UNWFCU3FlWFNMTFJwcFhXUVJBdVZ3VTUvVUYK
    QjdyKzhjOVkrM2hja0cxd1lORk1kelU9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata: 
  name: todo-tls-secret
  namespace: default
type: kubernetes.io/tls
