spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/todo
    username: todo_user
    password: PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    user: root
    password: PASSWORD
    url: jdbc:mysql://mysql-server:3306/todo?createDatabaseIfNotExist=true
    change-log: classpath:db/changelog/db.changelog-master.yaml